apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptoibero-dep
  labels:
    app: cryptoibero-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptoibero-api
  template:
    metadata:
      labels:
        app: cryptoibero-api
    spec:
      containers:
      - name: cryptoibero-api
        image: rafcasto/crypto-ibero-api:latest
        ports:
        - containerPort: 5001