apiVersion: v1
kind: Service
metadata:
  name: cryptoibero-svc
  labels:
    app: cryptoibero-api
spec:
  type: LoadBalancer 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: cryptoibero-api